# Generated by Django 6.0.1 on 2026-01-14 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_started', models.DateTimeField(verbose_name='date published')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='journalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('date_pub', models.DateTimeField(verbose_name='date published')),
                ('project_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.projectentry')),
            ],
        ),
    ]
